name: Golang CI/CD

on:
  push:
    branches:
      - master

env:
  GO111MODULE: on

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: Get current tag
        id: get_tag
        run: echo "::set-output name=TAG::$(git describe --tags --abbrev=0 2>/dev/null || echo '0.0.0')"

      - name: Get commit hash
        id: get_hash
        run: echo "::set-output name=HASH::$(git rev-parse --short HEAD)"

      - name: Build
        run: make build

      - name: Release
        uses: codfish/semantic-release-action@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
